global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: gateway
    metrics_path: /metrics
    static_configs:
      - targets: ['gateway:8080']

  - job_name: qrgen
    metrics_path: /metrics
    static_configs:
      - targets: ['qrgen:2112']
